# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(571, 537)
        self.download_button = QtWidgets.QPushButton(Form)
        self.download_button.setGeometry(QtCore.QRect(410, 480, 151, 31))
        self.download_button.setObjectName("download_button")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(90, 480, 301, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_path = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_path.setObjectName("label_path")
        self.horizontalLayout.addWidget(self.label_path)
        self.toolButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 460, 571, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_1.setObjectName("check_1")
        self.verticalLayout.addWidget(self.check_1)
        self.check_p1 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_p1.setObjectName("check_p1")
        self.verticalLayout.addWidget(self.check_p1)
        self.check_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_2.setObjectName("check_2")
        self.verticalLayout.addWidget(self.check_2)
        self.check_p2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_p2.setObjectName("check_p2")
        self.verticalLayout.addWidget(self.check_p2)
        self.check_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_3.setObjectName("check_3")
        self.verticalLayout.addWidget(self.check_3)
        self.check_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_4.setObjectName("check_4")
        self.verticalLayout.addWidget(self.check_4)
        self.check_5 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_5.setObjectName("check_5")
        self.verticalLayout.addWidget(self.check_5)
        self.check_all = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.check_all.setObjectName("check_all")
        self.verticalLayout.addWidget(self.check_all)

        self.retranslateUi(Form)
        self.check_1.clicked['bool'].connect(Form.on_select_1)
        self.check_p1.clicked['bool'].connect(Form.on_select_p1)
        self.check_2.clicked['bool'].connect(Form.on_select_2)
        self.check_p2.clicked['bool'].connect(Form.on_select_p2)
        self.check_3.clicked['bool'].connect(Form.on_select_3)
        self.check_4.clicked['bool'].connect(Form.on_select_4)
        self.check_5.clicked['bool'].connect(Form.on_select_5)
        self.check_all.clicked['bool'].connect(Form.on_select_all)
        self.download_button.clicked.connect(Form.on_click_download)
        self.toolButton.clicked.connect(Form.on_click_path_selector)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.download_button.setText(_translate("Form", "ダウンロード"))
        self.label_path.setText(_translate("Form", "保存先"))
        self.toolButton.setText(_translate("Form", "..."))
        self.check_1.setText(_translate("Form", "1"))
        self.check_p1.setText(_translate("Form", "p1"))
        self.check_2.setText(_translate("Form", "2"))
        self.check_p2.setText(_translate("Form", "p2"))
        self.check_3.setText(_translate("Form", "3"))
        self.check_4.setText(_translate("Form", "4"))
        self.check_5.setText(_translate("Form", "5"))
        self.check_all.setText(_translate("Form", "all"))
